CREATE TABLE "GCG_4353_Branch_Line"(
 "Branch" VARCHAR(9) NOT NULL ,
 "Customer" VARCHAR(6) NOT NULL ,
 "Branch_Name" VARCHAR(225),
 "B_Address1" VARCHAR(225),
 "B_Address2" VARCHAR(225),
 "B_City" VARCHAR(225),
 "B_State" VARCHAR(225),
 "B_Zip" VARCHAR(225),
 "B_Country" VARCHAR(225),
 "Channel_Type" VARCHAR(50),
 "Locale" VARCHAR(20),
 "Class_Code" VARCHAR(20),
 "Line_Access" VARCHAR(30),
 "Discount" VARCHAR(4),
 "Market" VARCHAR(50),
 "Territory" VARCHAR(30),
 "Internal_Region" VARCHAR(20),
 "Region" VARCHAR(20),
 "Field_Sales_Rep" VARCHAR(30),
 "National_Account" BIT NOT NULL ,
 "Dropped" BIT NOT NULL ,
 "Sales_Forecast_CY" NUMERIC(16,2));